name: frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^8.2.1
  provider: ^6.1.5+1
  http: ^1.6.0
  record: 5.1.2
  audioplayers: ^6.1.0
  path_provider: ^2.1.5
  speech_to_text: ^7.0.0
  flutter_tts: ^4.2.0
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4

dependency_overrides:
  record_platform_interface: 1.1.0
  path_provider_android: 2.2.23

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
